"""Sample document structure for testing, containing a variety of elements."""

from typing import Any

from rxllmproc.docs import types as docs_types
from rxllmproc.docs import docs_text

DOC_BODY = docs_types.Body(
    content=[
        docs_types.StructuralElement(
            startIndex=1,
            endIndex=1,
            sectionBreak=docs_types.SectionBreak(
                sectionStyle={
                    "columnSeparatorStyle": "NONE",
                    "contentDirection": "LEFT_TO_RIGHT",
                    "sectionType": "CONTINUOUS",
                }
            ),
        ),
        docs_types.StructuralElement(
            startIndex=1,
            endIndex=18,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=1,
                        endIndex=18,
                        textRun=docs_types.TextRun(
                            content="All Elements Doc\n",
                            textStyle=docs_types.TextStyle(),
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="TITLE",
                    headingId="h.rusrurcqkyed",
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=18,
            endIndex=19,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=18,
                        endIndex=19,
                        textRun=docs_types.TextRun(
                            content="\n",
                            textStyle=docs_types.TextStyle(),
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT",
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=19,
            endIndex=23,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=19,
                        endIndex=23,
                        textRun=docs_types.TextRun(
                            content="TOC\n",
                            textStyle=docs_types.TextStyle(),
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT",
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=23,
            endIndex=36,
            tableOfContents=docs_types.TableOfContents(
                content=[
                    docs_types.StructuralElement(
                        startIndex=24,
                        endIndex=35,
                        paragraph=docs_types.Paragraph(
                            elements=[
                                docs_types.ParagraphElement(
                                    startIndex=24,
                                    endIndex=33,
                                    textRun=docs_types.TextRun(
                                        content="Heading2\t",
                                        textStyle=docs_types.TextStyle(
                                            bold=True,
                                            foregroundColor=docs_types.ForegroundColor(
                                                color=docs_types.Color(
                                                    rgbColor=docs_types.RgbColor()
                                                )
                                            ),
                                            link=docs_types.Link(
                                                headingId="h.jd1elpngyb99"
                                            ),
                                        ),
                                    ),
                                ),
                                docs_types.ParagraphElement(
                                    startIndex=33,
                                    endIndex=34,
                                    textRun=docs_types.TextRun(
                                        content="1",
                                        textStyle=docs_types.TextStyle(
                                            bold=True,
                                            link=docs_types.Link(
                                                headingId="h.jd1elpngyb99"
                                            ),
                                        ),
                                    ),
                                ),
                                docs_types.ParagraphElement(
                                    startIndex=34,
                                    endIndex=35,
                                    textRun=docs_types.TextRun(
                                        content="\n",
                                        textStyle=docs_types.TextStyle(
                                            bold=True,
                                            foregroundColor=docs_types.ForegroundColor(
                                                color=docs_types.Color(
                                                    rgbColor=docs_types.RgbColor()
                                                )
                                            ),
                                        ),
                                    ),
                                ),
                            ],
                            paragraphStyle=docs_types.ParagraphStyle(
                                namedStyleType="NORMAL_TEXT"
                            ),
                        ),
                    )
                ]
            ),
        ),
        docs_types.StructuralElement(
            startIndex=36,
            endIndex=43,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=36,
                        endIndex=43,
                        textRun=docs_types.TextRun(
                            content="EndTOC\n",
                            textStyle=docs_types.TextStyle(),
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT",
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=43,
            endIndex=44,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=43,
                        endIndex=44,
                        textRun=docs_types.TextRun(
                            content="\n",
                            textStyle=docs_types.TextStyle(),
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT",
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=44,
            endIndex=114,
            table=docs_types.Table(
                columns=3,
                rows=3,
                tableRows=[
                    docs_types.TableRow(
                        startIndex=45,
                        endIndex=70,
                        tableCells=[
                            docs_types.TableCell(
                                startIndex=46,
                                endIndex=56,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=47,
                                        endIndex=56,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=47,
                                                    endIndex=56,
                                                    textRun=docs_types.TextRun(
                                                        content="Heading2\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="HEADING_2",
                                                headingId="h.jd1elpngyb99",
                                            ),
                                        ),
                                    )
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=56,
                                endIndex=59,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=57,
                                        endIndex=59,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=57,
                                                    endIndex=58,
                                                    dateElement=docs_types.DateElement(
                                                        dateId="kix.6qqmqoxth1t4",
                                                        textStyle=docs_types.TextStyle(),
                                                        dateElementProperties=docs_types.DateElementProperties(
                                                            timestamp="2026-02-13T12:00:00Z",
                                                            locale="en",
                                                            dateFormat="DATE_FORMAT_MONTH_DAY_YEAR_ABBREVIATED",
                                                            timeFormat="TIME_FORMAT_DISABLED",
                                                            displayText="Feb 13, 2026",
                                                        ),
                                                    ),
                                                ),
                                                docs_types.ParagraphElement(
                                                    startIndex=58,
                                                    endIndex=59,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                ),
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=59,
                                endIndex=70,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=60,
                                        endIndex=70,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=60,
                                                    endIndex=68,
                                                    textRun=docs_types.TextRun(
                                                        content="footnote",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                ),
                                                docs_types.ParagraphElement(
                                                    startIndex=68,
                                                    endIndex=69,
                                                    footnoteReference=docs_types.FootnoteReference(
                                                        footnoteId="kix.idiyz4dleh0l",
                                                        footnoteNumber="1",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                ),
                                                docs_types.ParagraphElement(
                                                    startIndex=69,
                                                    endIndex=70,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                ),
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                        ],
                    ),
                    # Row 2 and 3 omitted for brevity as they follow similar pattern,
                    # but included in full file generation below.
                    docs_types.TableRow(
                        startIndex=70,
                        endIndex=88,
                        tableCells=[
                            docs_types.TableCell(
                                startIndex=71,
                                endIndex=73,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=72,
                                        endIndex=73,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=72,
                                                    endIndex=73,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=73,
                                endIndex=86,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=74,
                                        endIndex=86,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=74,
                                                    endIndex=86,
                                                    textRun=docs_types.TextRun(
                                                        content="Normal text\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=86,
                                endIndex=88,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=87,
                                        endIndex=88,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=87,
                                                    endIndex=88,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                        ],
                    ),
                    # Row 3
                    docs_types.TableRow(
                        startIndex=88,
                        endIndex=113,
                        tableCells=[
                            docs_types.TableCell(
                                startIndex=89,
                                endIndex=91,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=90,
                                        endIndex=91,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=90,
                                                    endIndex=91,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=91,
                                endIndex=111,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=92,
                                        endIndex=93,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=92,
                                                    endIndex=93,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    ),
                                    docs_types.StructuralElement(
                                        startIndex=93,
                                        endIndex=110,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=93,
                                                    endIndex=110,
                                                    textRun=docs_types.TextRun(
                                                        content="Between newlines\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    ),
                                    docs_types.StructuralElement(
                                        startIndex=110,
                                        endIndex=111,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=110,
                                                    endIndex=111,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    ),
                                ],
                            ),
                            docs_types.TableCell(
                                startIndex=111,
                                endIndex=113,
                                content=[
                                    docs_types.StructuralElement(
                                        startIndex=112,
                                        endIndex=113,
                                        paragraph=docs_types.Paragraph(
                                            elements=[
                                                docs_types.ParagraphElement(
                                                    startIndex=112,
                                                    endIndex=113,
                                                    textRun=docs_types.TextRun(
                                                        content="\n",
                                                        textStyle=docs_types.TextStyle(),
                                                    ),
                                                )
                                            ],
                                            paragraphStyle=docs_types.ParagraphStyle(
                                                namedStyleType="NORMAL_TEXT",
                                                indentStart=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                                indentFirstLine=docs_types.Dimension(
                                                    0, "PT"
                                                ),
                                            ),
                                        ),
                                    )
                                ],
                            ),
                        ],
                    ),
                ],
            ),
        ),
        # Remaining paragraphs
        docs_types.StructuralElement(
            startIndex=114,
            endIndex=115,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=114,
                        endIndex=115,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=115,
            endIndex=117,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(startIndex=115, endIndex=116),
                    docs_types.ParagraphElement(
                        startIndex=116,
                        endIndex=117,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    ),
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=117,
            endIndex=118,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=117,
                        endIndex=118,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=118,
            endIndex=128,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=118,
                        endIndex=127,
                        textRun=docs_types.TextRun(
                            content="some link",
                            textStyle=docs_types.TextStyle(
                                foregroundColor=docs_types.ForegroundColor(
                                    color=docs_types.Color(
                                        rgbColor=docs_types.RgbColor(
                                            red=0.06666667,
                                            green=0.33333334,
                                            blue=0.8,
                                        )
                                    )
                                ),
                                link=docs_types.Link(
                                    url="http://www.google.com"
                                ),
                            ),
                        ),
                    ),
                    docs_types.ParagraphElement(
                        startIndex=127,
                        endIndex=128,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    ),
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=128,
            endIndex=129,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=128,
                        endIndex=129,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=129,
            endIndex=131,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=129,
                        endIndex=130,
                        horizontalRule=docs_types.HorizontalRule(
                            textStyle=docs_types.TextStyle()
                        ),
                    ),
                    docs_types.ParagraphElement(
                        startIndex=130,
                        endIndex=131,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    ),
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=131,
            endIndex=132,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=131,
                        endIndex=132,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=132,
            endIndex=134,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=132,
                        endIndex=133,
                        person=docs_types.Person(
                            personProperties={
                                "name": "info@gonser.ch",
                                "email": "info@gonser.ch",
                            },
                            textStyle=docs_types.TextStyle(),
                        ),
                    ),
                    docs_types.ParagraphElement(
                        startIndex=133,
                        endIndex=134,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    ),
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=134,
            endIndex=136,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=134,
                        endIndex=136,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=136,
            endIndex=137,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=136,
                        endIndex=137,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=137,
            endIndex=139,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=137,
                        endIndex=138,
                        richLink=docs_types.RichLink(
                            richLinkProperties={
                                "title": "Text structures",
                                "uri": "https://docs.google.com/document/u/0/d/1ZS6AoQcCCydFn955A6_yj8rSSNs-JwbHl8hMQTMizV0/edit",
                                "mimeType": "application/vnd.google-apps.document",
                            },
                            textStyle=docs_types.TextStyle(),
                        ),
                    ),
                    docs_types.ParagraphElement(
                        startIndex=138,
                        endIndex=139,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    ),
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=139,
            endIndex=140,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=139,
                        endIndex=140,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
        docs_types.StructuralElement(
            startIndex=140,
            endIndex=141,
            paragraph=docs_types.Paragraph(
                elements=[
                    docs_types.ParagraphElement(
                        startIndex=140,
                        endIndex=141,
                        textRun=docs_types.TextRun(
                            content="\n", textStyle=docs_types.TextStyle()
                        ),
                    )
                ],
                paragraphStyle=docs_types.ParagraphStyle(
                    namedStyleType="NORMAL_TEXT"
                ),
            ),
        ),
    ]
)

SAMPLE_DOC_JSON: Any = [
    {
        'level': 'text',
        'text': '',
        'start': 1,
        'end': 1,
        'heading_id': None,
        'subsections': [],
    },
    {
        'level': 'TITLE',
        'text': 'All Elements Doc\n',
        'start': 1,
        'end': 18,
        'heading_id': 'h.rusrurcqkyed',
        'subsections': [
            {
                'level': 'text',
                'text': '\nTOC\n\U0001ffffHeading2\t1\n\U0001ffffEndTOC\n\n\U0002ffff\U0003ffff\U0004ffffHeading2\n\U0004ffff\U0005ffff\n\U0004fffffootnote\U0006ffff\n\U0003ffff\U0004ffff\n\U0004ffffNormal text\n\U0004ffff\n\U0003ffff\U0004ffff\n\U0004ffff\nBetween newlines\n\n\U0004ffff\n\U0002ffff\n\U0006ffff\n\nsome link\n\n\U0006ffff\n\n\U0006ffff\n\ue907\n\n\U0006ffff\n\n\n',
                'start': 18,
                'end': 141,
                'heading_id': None,
                'subsections': [],
            }
        ],
    },
]

DOCS_TEXT = (
    f"{docs_text.NON_CHAR}All Elements Doc\n\nTOC\n{docs_text.NON_CHAR}Heading2\t1\n{docs_text.NON_CHAR}EndTOC\n\n"
    f"{docs_text.TABLE_START}{docs_text.TABLE_ROW}{docs_text.TABLE_CELL}Heading2\n{docs_text.TABLE_CELL}{docs_text.DATE_FILLER}\n"
    f"{docs_text.TABLE_CELL}footnote{docs_text.CHIP_FILLER}\n{docs_text.TABLE_ROW}{docs_text.TABLE_CELL}\n{docs_text.TABLE_CELL}"
    f"Normal text\n{docs_text.TABLE_CELL}\n{docs_text.TABLE_ROW}{docs_text.TABLE_CELL}\n{docs_text.TABLE_CELL}"
    f"\nBetween newlines\n\n{docs_text.TABLE_CELL}\n{docs_text.TABLE_START}\n{docs_text.CHIP_FILLER}\n\nsome link\n\n"
    f"{docs_text.CHIP_FILLER}\n\n{docs_text.CHIP_FILLER}\n\ue907\n\n{docs_text.CHIP_FILLER}\n\n\n"
)
