from typing import Any, List, Optional, Union, Dict, Iterator, Sequence, Type

class Z3Exception(Exception): ...

class CheckSatResult:
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...

sat: CheckSatResult
unsat: CheckSatResult
unknown: CheckSatResult

class SortRef:
    def name(self) -> str: ...

class FuncDeclRef:
    def name(self) -> str: ...
    def arity(self) -> int: ...
    def domain(self, i: int) -> SortRef: ...
    def range(self) -> SortRef: ...
    def __call__(self, *args: Any) -> 'ExprRef': ...

class ExprRef:
    def decl(self) -> FuncDeclRef: ...
    def __eq__(self, other: Any) -> 'ExprRef': ...
    def __ne__(self, other: Any) -> 'ExprRef': ...
    def __lt__(self, other: Any) -> 'ExprRef': ...
    def __gt__(self, other: Any) -> 'ExprRef': ...
    def __call__(self, *args: Any) -> 'ExprRef': ...

# Simplified for our usage since most ExprRefs can be BoolRefs
BoolRef = ExprRef
ArithRef = ExprRef

class ModelRef:
    def decls(self) -> List[FuncDeclRef]: ...
    def __getitem__(self, item: Union[ExprRef, FuncDeclRef]) -> ExprRef: ...
    def __iter__(self) -> Iterator[FuncDeclRef]: ...
    def __len__(self) -> int: ...

class Solver:
    def __init__(self) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def push(self) -> None: ...
    def pop(self, n: int = 1) -> None: ...
    def add(self, *args: Union[ExprRef, Sequence[ExprRef]]) -> None: ...
    def assert_and_track(
        self, assertion: ExprRef, label: Union[str, ExprRef]
    ) -> None: ...
    def check(self, *args: ExprRef) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def unsat_core(self) -> List[ExprRef]: ...
    def to_smt2(self) -> str: ...
    def reset(self) -> None: ...

def Int(name: str) -> ArithRef: ...
def Real(name: str) -> ArithRef: ...
def Bool(name: str) -> BoolRef: ...
def Const(name: str, sort: SortRef) -> ExprRef: ...
def IntSort() -> SortRef: ...
def RealSort() -> SortRef: ...
def BoolSort() -> SortRef: ...
def DeclareSort(name: str) -> SortRef: ...
def Function(name: str, *sorts: SortRef) -> FuncDeclRef: ...
def Or(*args: Union[ExprRef, List[ExprRef]]) -> BoolRef: ...
def And(*args: Union[ExprRef, List[ExprRef]]) -> BoolRef: ...
def Not(arg: ExprRef) -> BoolRef: ...
def parse_smt2_string(
    s: str,
    sorts: Optional[Dict[str, SortRef]] = None,
    decls: Optional[Dict[str, FuncDeclRef]] = None,
) -> List[ExprRef]: ...
